CREATE DATABASE Exercicio1_4

USE Exercicio1_4

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50)NOT NULL,
	Email VARCHAR(50)NOT NULL,
	Senha VARCHAR(50)NOT NULL,
	Permissao VARCHAR(50)NOT NULL
)

CREATE TABLE Artista
(
	IdArtista INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50)NOT NULL
)

CREATE TABLE Album
(
	IdAlbum INT PRIMARY KEY IDENTITY,
	IdaArtista INT FOREIGN KEY REFERENCES Artista(IdArtista),
	Titulo VARCHAR(50) NOT NULL,
	DataLancamento DATE NOT NULL,
	Localizacao VARCHAR(50) NOT NULL,
	QtdMinutos VARCHAR(50) NOT NULL,
	Ativo VARCHAR(50) NOT NULL
)

CREATE TABLE Estilo
(
	IdEstilo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL
)

CREATE TABLE AlbumEstilo
(
	IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum),
	IdEstilo INT FOREIGN KEY REFERENCES Estilo(IdEstilo)
)

