CREATE DATABASE Exercicio1_3

USE Exercicio1_3

CREATE TABLE Tipo
(
	IdTipo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50)NOT NULL
)

CREATE TABLE Raca
(
	IdRaca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50)NOT NULL
)

CREATE TABLE Dono
(
	IdDono INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50)NOT NULL
)

CREATE TABLE Pet
(
	IdPet INT PRIMARY KEY IDENTITY,
	IdTipo INT FOREIGN KEY REFERENCES Tipo(IdTipo),
	IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca),
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
	Nome VARCHAR(50)NOT NULL,
	DataNascimento DATE NOT NULL
)

CREATE TABLE Endereco
(
	IdEndereco INT PRIMARY KEY IDENTITY,
	Rua VARCHAR(50)NOT NULL,
	Bairro VARCHAR(50)NOT NULL,
	Estado VARCHAR(50)NOT NULL
)

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	IdEndereco INT FOREIGN KEY REFERENCES Endereco(IdEndereco),
	Nome VARCHAR(50)NOT NULL
)

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY, 
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
	CRMV VARCHAR(50)NOT NULL,
	Nome VARCHAR(50)NOT NULL
)

CREATE TABLE Consulta
(
	IdConsulta INT PRIMARY KEY IDENTITY,
	IdPet INT FOREIGN KEY REFERENCES Pet(IdPet),
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),
	DataConsulta DATE NOT NULL,
	Protocolo VARCHAR NOT NULL
)
